# Generated by Django 5.2.17 on 2026-09-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_consultation_system_checks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='abdomen_pelvis',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='breasts',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='cardiac',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='genitourinary',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='gynecological_exam',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='lower_extremities',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='lung_fields',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='musculoskeletal',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='neurological_exam',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='rectal_exam',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='rib_cage',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='thorax',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='upper_extremities',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='abdomen_pelvis',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='breasts',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='cardiac',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='genitourinary',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='gynecological_exam',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='lower_extremities',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='lung_fields',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='musculoskeletal',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='neurological_exam',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='rectal_exam',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='rib_cage',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='thorax',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='upper_extremities',
        ),
    ]
