# Generated by Django 5.2.17 on 2026-09-16 19:55

from django.db import migrations


def move_illness_history(apps, schema_editor):
    alias = schema_editor.connection.alias
    consultations = apps.get_model('patients', 'Consultation').objects.using(alias)
    records = apps.get_model('patients', 'ClinicalRecord').objects.using(alias)
    seen = set()
    for consultation in consultations.exclude(present_illness_history='').order_by(
        'patient_id', '-date', '-time', '-created_at', '-pk',
    ).iterator():
        history = consultation.present_illness_history
        if consultation.patient_id in seen or not history.strip():
            continue
        seen.add(consultation.patient_id)
        record, created = records.get_or_create(
            patient_id=consultation.patient_id,
            defaults={'present_illness_history': history},
        )
        if not created and not record.present_illness_history.strip():
            records.filter(pk=record.pk).update(present_illness_history=history)


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_remove_unused_examination_fields'),
    ]

    operations = [
        migrations.RunPython(move_illness_history, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='consultation',
            name='present_illness_history',
        ),
    ]
