# Generated by Django 5.2.17 on 2026-09-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_move_illness_history_to_clinical_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='observations_analysis',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='observations_analysis',
        ),
    ]
