# Generated by Django 5.2.17 on 2026-09-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_remove_observations_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='treatment_performed',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='treatment_performed',
        ),
    ]
