# Generated by Django 5.2.17 on 2026-09-16 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_remove_treatment_performed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='cema_number',
        ),
        migrations.RemoveField(
            model_name='clinicalrecord',
            name='inss_number',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='cema_number',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='inss_number',
        ),
    ]
