# Generated by Django 5.2.17 on 2026-09-17 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_remove_inss_and_cema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=1000)),
                ('content', models.TextField(max_length=10000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_amendments', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amendments', to='patients.consultation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=255)),
                ('resource_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_revisions', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_revisions', to='patients.consultation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_revisions', to='patients.patient')),
            ],
            options={
                'ordering': ('-id',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('consultation__isnull', True)), fields=('patient', 'resource_version'), name='clinical_record_revision_uniq'), models.UniqueConstraint(condition=models.Q(('consultation__isnull', False)), fields=('consultation', 'resource_version'), name='consultation_revision_uniq')],
            },
        ),
    ]
