# Generated by Django 5.2.17 on 2026-10-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0026_protect_clinical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_place',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino'), ('OTRO', 'Otro')], max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
