# Generated by Django 5.2.17 on 2026-09-17 05:24

from django.db import migrations, models
from django.contrib.postgres.constraints import ExclusionConstraint


class AddPortableField(migrations.AddField):
    """SQLite rebuilds tables on add-field; keep PostgreSQL-only SQL out."""
    def portable_state(self, state, schema_editor):
        if schema_editor.connection.vendor != "sqlite":
            return state
        state = state.clone()
        model = state.models[("appointments", "appointment")]
        model.options["constraints"] = [item for item in model.options.get("constraints", []) if not isinstance(item, ExclusionConstraint)]
        model.fields["scheduled_range"] = model.fields["scheduled_range"].clone()
        model.fields["scheduled_range"].null = True
        state.reload_model("appointments", "appointment", delay=False)
        return state

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        super().database_forwards(app_label, schema_editor, self.portable_state(from_state, schema_editor), self.portable_state(to_state, schema_editor))

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        super().database_backwards(app_label, schema_editor, self.portable_state(from_state, schema_editor), self.portable_state(to_state, schema_editor))


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointmentrescheduleevent_and_more'),
    ]

    operations = [
        AddPortableField(
            model_name='appointment',
            name='check_in_previous_status',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
        AddPortableField(
            model_name='appointment',
            name='version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
    ]
