# Generated by Django 5.2.17 on 2026-09-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicprofile',
            name='tagline',
        ),
    ]
