# Generated by Django 5.2.17 on 2026-09-17 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_remove_clinic_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='clinicservice',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='clinic_service_nonnegative_price'),
        ),
    ]
